### ISSUE TITLE
Refactoring generate code method

### ISSUE THREAD

**Issue by POPPIN-FUMI** [EpicsDAO/zapp#10]
@JonasCir made a great refactoring🎉
Let's update all the generation methods.

Example:

Old

`create_entity`
https://github.com/EpicsDAO/zapp/blob/main/src/g/entity.rs#L13

Good
`create_migration`
https://github.com/EpicsDAO/zapp/blob/main/src/g/migration.rs#L16

**Comment by JonasCir** [comment]
Hey thanks for the shout out, I appreciate :)

**Comment by POPPIN-FUMI** [comment]
Now we launched Epics Alpha !

https://alpha.epics.dev

This issue has 3000 $EPCT as a prize! 
Please have a look at this website ;)

**Comment by JonasCir** [comment]
@POPPIN-FUMI Cool will give it a shot! :D
