### ISSUE TITLE
Remove async/await for now

### ISSUE THREAD

**Issue by JonasCir** [EpicsDAO/zapp#12]
Currently, async/await is used all over the place, however, it does not provide **any** advantage b/c we do not submit any task to an executor or used any concurrency.

I argue that we should _selectively_ re-introduce it properly in parts where it actually makes sense.

You can refer to this resource to learn [more](https://rust-lang.github.io/async-book/06_multiple_futures/01_chapter.html).

**Comment by POPPIN-FUMI** [comment]
Yeah if it's not a big work it would be awesome.
But so far, I have prioritized building scalable apps faster. 
Do you think you can implement this?

**Comment by JonasCir** [comment]
No big work.
I totally agree what you said about scalable apps, but right now I tend to get a solid foundation and then see where async provides benefit. Right now, I had issues that I could program some stuff the way I would like to b/c async interfering :)

#13 is up

**Comment by POPPIN-FUMI** [comment]
oh that's so fast! 
yea true solid foundation at the beginning is important !
I will check them later. Thank you!
