### ISSUE TITLE
Use `quote` to generate Rust code instead of string format

### ISSUE THREAD

**Issue by JonasCir** [EpicsDAO/zapp#2]
Hi there,
thank you for creating this project, it looks super useful!

While going through the code generation done in `g`, I noticed that the Rust code generation is done through plain string formatting. I also worked on a small project where I needed to generate Rust code and I resorted to this approach at first as well. However, I quickly ran into problems like code generation being dependent on conditionals quickly resulting in annoying string concatenations.

I decided to use the popular [quote](https://github.com/dtolnay/quote#syntax) library to template Rust code in a clean manner, making my life a lot easier and the code cleaner to read (I also used [prettyplease](https://github.com/dtolnay/prettyplease) to auto-format the generated code).

Maybe this is helpful, but feel free to close if this project goes with the format approach.

My project is here for reference: https://github.com/JonasCir/java2rs

**Comment by POPPIN-FUMI** [comment]
HI Jonasan! Thank you for your committing.
Yes, that formatting looks better. I will check it soon!
I need to update doc site also.
Thank you very much.

**Comment by POPPIN-FUMI** [comment]
Hi. I accidentally merged it to main when I tried to test.
I reverted that commit since there were some errors when running `cargo run g user`.
Sorry for your inconvenience... Could you please make a PR again? 
Then I will migrate code generation way to the new one.
Thank you!

**Comment by JonasCir** [comment]
Hey, thank you for the prompt reply. All good, here we go #4 :)
