### ISSUE TITLE
Is there any way to include initial file in cargo package?

### ISSUE THREAD

**Issue by POPPIN-FUMI** [EpicsDAO/zapp#6]
`zapp new` downloads the initial file from Google Cloud Storage at this moment.

[https://github.com/EpicsDAO/zapp/blob/5d9f951f8953b62dc5b57d6ca47966e9d00d2198/src/init/process.rs#L126](https://github.com/EpicsDAO/zapp/blob/5d9f951f8953b62dc5b57d6ca47966e9d00d2198/src/init/process.rs#L126)

This initial folder is just 23KB. 
I want to have it in the local machine when cargo install zapp.

**Comment by JonasCir** [comment]
Agreed :+1: I was wondering what this function was doing. 

I think we can template the rust code through `quote` directly. Other resources can just be formatted/printed or we find a way to include assets in cargo crates (I know there are ways, but needs investigation how to do this cleanly).

**Comment by POPPIN-FUMI** [comment]
Yeah, Awesome!
This also has a quest here;
[https://alpha.epics.dev/ja/quest/UXVlc3Q6NA==/](https://alpha.epics.dev/ja/quest/UXVlc3Q6NA==/)
